server:
  port: 8080
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cart
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/cart/**
        - id: inventory
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/inv/**